name: Build APK FIX
on: workflow_dispatch:
jobs: build: runs-on: ubuntu-22.04
steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Install system dependencies
    run: |
      sudo apt update
      sudo apt install -y git zip unzip openjdk-17-jdk python3-pip \
      autoconf automake libtool pkg-config

  - name: Install Buildozer
    run: |
      pip3 install --upgrade pip
      pip3 install cython==0.29.36 buildozer

  - name: Accept Android SDK licenses
    run: |
      mkdir -p $HOME/.android
      echo "y" | sudo yes | true

  - name: Build APK
    run: |
      export ANDROIDSDK="$HOME/.buildozer/android/platform/android-sdk"
      export ANDROIDNDK="$HOME/.buildozer/android/platform/android-ndk-r25b"
      export ANDROIDAPI=33
      export ANDROIDMINAPI=21

      buildozer -v android debug

  - name: Upload APK
    uses: actions/upload-artifact@v4
    with:
      name: apk
      path: bin/*.apk
