name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install system packages
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk \
          python3-pip autoconf automake libtool pkg-config \
          zlib1g-dev libffi-dev libssl-dev

      - name: Install Buildozer
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install buildozer cython==0.29.36

      - name: Fix Android SDK licenses
        run: |
          mkdir -p $HOME/.android
          echo "count=0" > $HOME/.android/repositories.cfg

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
